Fix compilation of module03 + new Makefile

diff --git a/module03/ex01/Makefile b/module03/ex01/Makefile
--- a/module03/ex01/Makefile
+++ b/module03/ex01/Makefile
@@ -3,40 +3,84 @@
 #                                                         :::      ::::::::    #
 #    Makefile                                           :+:      :+:    :+:    #
 #                                                     +:+ +:+         +:+      #
-#    By: danimart <danimart@student.42.fr>          +#+  +:+       +#+         #
+#    By: daniema3 <daniema3@student.42madrid.com    +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2024/01/11 15:38:17 by danimart          #+#    #+#              #
-#    Updated: 2024/02/20 15:24:11 by danimart         ###   ########.fr        #
+#    Updated: 2025/08/11 19:19:16 by daniema3         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
 NAME = scavtrap
 
+SRC_DIR = .
+OBJ_DIR = ./objs
+
 CC = c++
-CPPFLAGS = -Wall -Wextra -Werror -std=c++98 -pedantic
+CFLAGS =	-Wall -Werror -Wextra \
+			-std=c++98 -pedantic \
+			-MMD \
+			-fdiagnostics-color=always \
 
-SRCS = \
-		main.cpp \
-		ClapTrap.cpp \
-		ScavTrap.cpp
+SRCS =	ClapTrap.cpp \
+		ScavTrap.cpp \
+		main.cpp
 
-OBJS := $(SRCS:%.cpp=%.o)
+# > ~ Colors
+
+RED = \e[0;31m
+BRED = \e[1;31m
+GREEN = \e[1;32m
+YLW = \e[0;33m
+BYLW = \e[1;33m
+BLUE = \e[1;36m
+GRAY = \e[0;30m
+RES = \e[0m                                                                   
+
+WNAME = $(BYLW)$(NAME)$(YLW)
+OKNAME = $(BLUE)$(NAME)$(GREEN)
+
+# > ~ Project compilation
+
+SRCS := $(addprefix $(SRC_DIR)/, $(SRCS))
+
+OBJS = $(SRCS:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
+
+$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
+	@mkdir -p $(dir $@)
+	@echo -n "\r⏳ $(YLW)Compiling $(notdir $<)$(GRAY)...$(RES)"
+	@{\
+		ERR=$$( ($(CC) $(CFLAGS) -c $< -o $@) 2>&1 );\
+		if [ $$? -ne 0 ]; then\
+			echo -n "\r❌ $(RED)Failed to compile $(BRED)$(notdir $<)";\
+			echo -n "$(GRAY):$(RES)";\
+			echo "\n$$ERR";\
+			exit 1;\
+		fi;\
+	}
 
 all: $(NAME)
 
 $(NAME): $(OBJS)
-	$(CC) $(CPPFLAGS) $(OBJS) -o $@
+	@$(CC) $(CFLAGS) $(OBJS) -o $(NAME)
+	@echo -n "\r✅ $(OKNAME) $(GREEN)successfully compiled!$(RES)"
+	@echo 
+
+# > ~ Clean project files
 
 clean:
-	$(RM) $(OBJS)
+	@echo -n "\r⏳ $(YLW)Removing $(WNAME) objs$(GRAY)...$(RES)"
+	@rm -rf $(OBJ_DIR)
+	@echo -n "\r✅ $(GREEN)Removed $(OKNAME) objs$(GRAY).$(RES)"
+	@echo 
 
 fclean: clean
-	rm -rf $(NAME)
+	@echo -n "\r⏳ $(YLW)Removing $(WNAME) executable$(GRAY)...$(RES)"
+	@rm -rf $(NAME)
+	@echo -n "\r✅ $(GREEN)Removed $(OKNAME) executable\$(GRAY).$(RES)"
+	@echo 
 
-re: fclean all
+# > ~ Clean and compile
 
-red: fclean debug
+re: fclean $(NAME)
 
-res: fclean sanitize
-
-.PHONY: sanitize debug res red re clean fclean all
+.PHONY: all clean fclean re
